services:
  meubanco:
    image: mysql:5.7
    container_name: banco-cfbCursos
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SENHA}
      MYSQL_DATABASE: ${DB_NOME}
    volumes:
      - dados-mysql:/var/lib/mysql

  minhabase:
    image: adminer:latest
    container_name: minha-base
    ports:
      - ${PORTA_ADMINER}:8080
    depends_on:
      - meubanco

volumes:
  dados-mysql:
